FROM action-runner-base as action-runner

ARG CONTAINER_INSTALL_USER
ARG CONTAINER_RUN_USER

ENV CONTAINER_INSTALL_USER=${CONTAINER_INSTALL_USER:-0}
ENV CONTAINER_RUN_USER=${CONTAINER_RUN_USER:-0}

USER $CONTAINER_INSTALL_USER

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git curl

USER $CONTAINER_RUN_USER
